export { default as EditTableDialog } from './EditTableDialog'
export { default as ReservationDialog } from './ReservationDialog'
export { default as OccupiedDialog } from './OccupiedDialog'
export { default as CleaningDialog } from './CleaningDialog'
export { default as AvailableDialog } from './AvailableDialog'
export { default as AddTableDialog } from './AddTableDialog'
